export const GET_RESTAURANTES = "GET_RESTAURANTES";
export const GET_PLATOS = "GET_PLATOS";
export const POST_DETALLES = "POST_DETALLES";
export const POST_ORDEN = "POST_ORDEN";
export const DELETE_ORDEN = 'DELETE_ORDEN'
